/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.*;

public class App {
    public String getGreeting() {
        return "Hello World, this ";
    }
    static final String QUERY = "select  * from cars";

    static final String DB_URL = "jdbc:postgresql://localhost:5432/postgres";
    static final String USER = "postgres";
    static final String PASS = "admin";

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        try (Connection connection = DriverManager.getConnection(DB_URL, USER, PASS);) {
            // Code here.
            System.out.println("Connected to the PostgreSQL server successfully.");
            Statement statement = connection.createStatement();
            var selectAllResult = statement.executeQuery(QUERY);

            while (selectAllResult.next()){
                System.out.println("make= " + selectAllResult.getString("make"));
            }
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }


    }
}
